# Generated by Django 3.1.6 on 2022-03-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('футболки', 'футболки'), ('худи', 'худи'), ('Другое', 'Другое')], default=1, max_length=9),
            preserve_default=False,
        ),
    ]
