# Generated by Django 3.1.6 on 2022-04-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('футболки', 'футболки'), ('кофты', 'кофты'), ('Другое', 'Другое')], default='Другое', max_length=9),
        ),
    ]
