# Generated by Django 3.1.6 on 2022-04-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220407_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='card_item',
        ),
    ]
