# Generated by Django 3.1.6 on 2022-04-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_cartproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], default='M', max_length=1),
        ),
    ]
